spring:
  application:
    name: ln-table
  jackson:
    mapper:
      default-view-inclusion: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 15000ms
    jedis:
      pool:
        max-idle: 200
        min-idle: 200
        max-active: 2000
        max-wait: 1000ms
